### PR TITLE
Added Voice Recognition

### PR DESCRIPTION
**Pull request by masamune-prog**
Added voice recognition input. This can help unlock new uses like practicing English pronunciations. This is my first pull request so feel free to critique my code. Looking to add support for other languages like Chinese and French

### CODE REVIEW

**Comment by jongomez** [comment]
This is really cool :star_struck:

Code is looking good so far in my opinion. One thing I'd change is: I'd remove the package-lock.json file, as I don't think it's necessary :thinking: . Running `yarn` on the root directory of this project should install the dependencies and update the yarn.lock file, which should be enough. But please correct me if I'm wrong.

I noticed you set this PR as draft - if there's anything I can do, any issues you're having or anything else, please let me know.

**Comment by masamune-prog** [comment]
Thanks for the kind words and offer to help . The package-lock.json was likely added automatically as a result of some npm command I ran while testing other methods to make the voice recognition more accurate. It can be removed safely. 
Awesome code especially with the animations, looks more lifelike than even paid options like visme.

**Comment by jongomez** [comment]
Thank you. I will try to merge this as soon as possible. I'll add a dropdown with multiple speech recognition languages in the settings menu. I'll also do some minor updates on the UI, and add some logic for cases where there is already a typed message in the text box, etc.

**Review by jongomez — APPROVED** [review]
Merging this now. Will add another commit with some minor updates. 

If there's any feature or anything else you'd like to see, let me know.

Thanks again for the PR :pray:

**Pull request merged**
